package org.predictiveedge.decision.domain;

public enum DecisionReason {
    RECOMMENDATION_APPROVED,
    DECISION_ABSTAINED,
    MISSING_INTELLIGENCE_FEEDBACK,
    INTELLIGENCE_NOT_READY,
    INTELLIGENCE_VETO,
    DIRECTION_CONFLICT,
    TRADER_INTENT_NOT_ACTIVE,
    DIRECTION_NOT_PERMITTED
}
